// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkM3EG62LgRf2XfJNRI-mih1151mwie1U',
    appId: '1:107271813889:web:b09ac0ee1d5092d37e7900',
    messagingSenderId: '107271813889',
    projectId: 'e-learning-93242',
    authDomain: 'e-learning-93242.firebaseapp.com',
    storageBucket: 'e-learning-93242.appspot.com',
    measurementId: 'G-3EE1ST4C3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4WB2XKvsqbFufH6_d2scIvK340dhGIaE',
    appId: '1:107271813889:android:e8081781761dd0d77e7900',
    messagingSenderId: '107271813889',
    projectId: 'e-learning-93242',
    storageBucket: 'e-learning-93242.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlJgWbsbv_s1mIXKFVel4rXzJdZEWKys0',
    appId: '1:107271813889:ios:9a68c4e6ba5225c67e7900',
    messagingSenderId: '107271813889',
    projectId: 'e-learning-93242',
    storageBucket: 'e-learning-93242.appspot.com',
    iosClientId: '107271813889-9jgpb42bdehr59gl23ccdeg17i5ngrr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlJgWbsbv_s1mIXKFVel4rXzJdZEWKys0',
    appId: '1:107271813889:ios:b4a73d58db19902d7e7900',
    messagingSenderId: '107271813889',
    projectId: 'e-learning-93242',
    storageBucket: 'e-learning-93242.appspot.com',
    iosClientId: '107271813889-8hh5g4uoe2vfptgpkrtlc5f1i127g20c.apps.googleusercontent.com',
    iosBundleId: 'com.example.eLearningApp.RunnerTests',
  );
}
